version: '3.7'

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  nginx_primary:
    image: nginx
    container_name: nginx_primary
    hostname: nginx_primary
    volumes:
      - ./primary.conf:/etc/nginx/conf.d/default.conf
      - ./primary.html:/usr/share/nginx/html/index.html
    ports:
      - "8881:80"
    expose:
      - 80
    networks:
      frontend:
        ipv4_address: 192.168.1.151

  nginx_secondary_1:
    image: nginx
    container_name: nginx_secondary_1
    hostname: nginx_secondary_1
    volumes:
      - ./secondary_1.conf:/etc/nginx/conf.d/default.conf
      - ./secondary_1.html:/usr/share/nginx/html/index.html
    ports:
      - "8882:80"
    expose:
      - 80
    networks:
      frontend:
        ipv4_address: 192.168.1.152

  nginx_secondary_2:
    image: nginx
    container_name: nginx_secondary_2
    hostname: nginx_secondary_2
    volumes:
      - ./secondary_2.conf:/etc/nginx/conf.d/default.conf
      - ./secondary_2.html:/usr/share/nginx/html/index.html
    ports:
      - "8883:80"
    expose:
      - 80
    networks:
      frontend:
        ipv4_address: 192.168.1.153

  nginx_secondary_3:
    image: nginx
    container_name: nginx_secondary_3
    hostname: nginx_secondary_3
    volumes:
      - ./secondary_3.conf:/etc/nginx/conf.d/default.conf
      - ./secondary_3.html:/usr/share/nginx/html/index.html
    ports:
      - "8884:80"
    expose:
      - 80
    networks:
      frontend:
        ipv4_address: 192.168.1.154
