version: '3.7'

services:
  primary:
    image: nginx
    container_name: nginx_primary
    hostname: nginx_primary
    volumes:
      - ./primary.conf:/etc/nginx/conf.d/default.conf
      - ./primary.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8881:80"
